### ISSUE TITLE
Setting the logger's progname breaks syslog loggers

### ISSUE THREAD

**Issue by pinkertonpg** [jdwyah/ratelimit-ruby#1]
https://github.com/jdwyah/ratelimit-ruby/blob/master/lib/ratelimit-ruby.rb#L22
```
@logger = (logger || Logger.new($stdout)).tap do |log|
  log.progname = "RateLimit"
end
```

`Syslog::Logger`s have no `progname` attribute, so this fails with the following error:
```
undefined method `progname=' for #<Syslog::Logger:0x007f1a9e188a20>`
```

**Comment by jdwyah** [comment]
👍 

resolved in https://github.com/jdwyah/ratelimit-ruby/commit/12c0413a63e1c305d58eda57bf875b467e99af1f

released in 0.1.13
